INSERT INTO LIVRO(TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO )
 VALUES ('O Senhor dos Anéis', 'J.R.R. Tolkien', true, '2023-10-01');

 INSERT INTO LIVRO(TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO )
 VALUES ('SPRINGbOOT AVANÇADO', 'Professor', FALSE, null);

 INSERT INTO LIVRO(TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO )
 VALUES ('Harry Potter', 'J.K. Rowling', FALSE, null);

 INSERT INTO LIVRO(TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO )
 VALUES ('DC', 'Worner', FALSE, null);